version: "3.9"

services:
  postgres:
    image: myapp-postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-app:
    build: .
    image: myapp-go-app:latest
    depends_on:
      postgres:
        condition: service_healthy

  go-test:
    build: .
    image: myapp-go-test:latest
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
