services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "0.0.0.0:5432:5432"
      - "[::]:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      postgres:
        condition: service_healthy
    command: ["go", "run", "main.go"]

  go-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      postgres:
        condition: service_healthy
    command: ["go", "test", "-v", "./..."]

volumes:
  postgres_data:
