// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"database/sql"
)

type AccountsBank struct {
	ID        int32
	FullName  string
	CreatedAt sql.NullTime
}
