name: Go CI with Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Build and start services with Docker Compose
      run: |
        docker compose build --no-cache

    - name: Run tests with Docker Compose
      run: |
        docker compose up --exit-code-from go-test

    # - name: Shutdown services
    #   if: always()
    #   run: docker compose down -v
